Feat : get product data, filtering market list
Wecloset/pandaFE pull request #24
Opened 2023-02-23 08:43 UTC by rlorxl

1. get product data - useQuery이용
2. context추가 : 마켓 필터링 리스트 관리용 + 필터링 로직
3. market관련 컴포넌트들 분리, jsx정리 / 수정
4. 게시물작성페이지 validation추가
5. next.config.ts옵션 추가 (Next Image 사용할 때 동적인 경로 넣어줄 때 필요한 옵션입니다)

2023-02-23 09:01 UTC, jiji-hoon96 requested changes
상품등록할때 가격입력하는거 예외처리 되어있는지 확인해서 아에 숫자만 입력하게하든지 오류걸리게하든지 예외처리하는게 조아보임~

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/components/market/filter-list.tsx
> +    ) : null;
삼항연산자에서 null 이나 undefined 쓰는것보다 "" 하라고했던거같은데 확인부탁합니다
(정확한지식은아님)

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/components/market/filter-list.tsx
> +              <Icon icon="ic:baseline-clear" aria-label="검색어 삭제" onClick={() => removeWord(item)} />
onClick 에서 직접 함수할당하는게 어떨까싶어요

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/components/market/market-list.tsx
> +  const { isLoading, isError, data, error } = useQuery("products", getAllProducts);
여기서 data 빼고 다안쓰는데 날리는게 조을듯싶어유

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/pages/market/index.tsx
> +            <FilterOverlay closeOverlay={closeFilterOverlay} />
여기서 직접할당해서 closeOverlay={setFilterOpen(false)} 하면 error 대나요?

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/store/filter-context.tsx
> +  useEffect(() => {
지우삼

2023-02-23 09:01 UTC, jiji-hoon96 commented on src/store/filter-context.tsx
> +        (product: any) =>
any?!?!??!?!??!?!?!?!?!?!!?!?!!??!!

2023-02-23 10:07 UTC, rlorxl commented
상품등록할때 가격입력 예외처리 추가했어요!

2023-02-24 18:04 UTC, rlorxl commented
conflict생긴게 react-loader-spinner때문이어서 지훈님이 봐주시는게 조을거같아요. 코멘트 남기신건 수정할게요

2023-02-24 18:04 UTC, rlorxl commented on src/store/filter-context.tsx
> +  useEffect(() => {
수정완료

2023-02-24 18:04 UTC, rlorxl commented on src/store/filter-context.tsx
> +        (product: any) =>
수정완료

2023-02-24 18:07 UTC, rlorxl commented on src/components/market/market-list.tsx
> +  const { isLoading, isError, data, error } = useQuery("products", getAllProducts);
✔️

2023-02-24 18:09 UTC, rlorxl commented on src/components/market/filter-list.tsx
> +              <Icon icon="ic:baseline-clear" aria-label="검색어 삭제" onClick={() => removeWord(item)} />
넹 로직이 하나라서 수정하는게 나을거같네요

2023-02-27 13:40 UTC, merged